// src/content/talleres.js

export const TALLERES = [
    {
        id: "corresponsabilidad-laboral-familiar-personal",
        title: "Corresponsabilidad laboral, familiar y personal",
        subtitle: "Taller corporativo",
        description:
            "Taller corporativo para impulsar prácticas de corresponsabilidad y bienestar en el entorno laboral.",
        href: "/files/talleres/sabermas/DETERMINARACCIONESDECORRESPONSABILIDADLABORALFAMILIARYPERSONAL.pdf",
        videoUrl: "https://www.youtube.com/embed/N8yu8Xtf-VM",
        mainImage: "/images/talleres/TALLER_CORRESPONSABILIDAD.jpeg",
        badgeTop: "/files/talleres/confianza/CERTIFICADOPORMAXAN.png",
        badgeBottom: "/files/talleres/confianza/AVALADOPORIMPULSOCOMPLETO.png",
        esquemaImage:
            "/files/talleres/comofunciona/CORPORATIVOPARADETERMINARACCIONESDECORRESPONSABILIDADLABORALFAMILIARYPERSONAL.jpeg",
        paraQuienImage: "/files/talleres/esparati/ESPARA TI_TALLERES-01.jpg.jpeg",
        duration: "3 horas",
        metaLeft: "Taller corporativo",
        badge: "Taller",
        keywords: [
            "corresponsabilidad",
            "bienestar",
            "familia",
            "personal",
            "laboral",
            "equilibrio",
        ],
    },
    {
        id: "prevenir-violencia-laboral",
        title: "Prevenir la violencia laboral",
        subtitle: "Taller corporativo",
        description:
            "Taller corporativo para identificar, prevenir y atender conductas de violencia laboral en el centro de trabajo.",
        href: "/files/talleres/sabermas/CORPORATIVOPARAPREVENIRLAVIOLENCIALABORAL.pdf",
        videoUrl: "https://www.youtube.com/embed/N8yu8Xtf-VM",
        mainImage: "/images/talleres/TALLER_VIOLENCIA_LABORAL.jpeg",
        badgeTop: "/files/talleres/confianza/CERTIFICADOPORMAXAN.png",
        badgeBottom: "/files/talleres/confianza/AVALADOPORIMPULSOCOMPLETO.png",
        esquemaImage:
            "/files/talleres/comofunciona/CORPORATIVOPARAPREVENIRLAVIOLENCIALABORAL.jpeg",
        paraQuienImage: "/files/talleres/esparati/ESPARA TI_TALLERES-02.jpg.jpeg",
        duration: "6 horas",
        metaLeft: "Taller corporativo",
        badge: "Taller",
        keywords: [
            "violencia laboral",
            "prevención",
            "acoso",
            "hostigamiento",
            "entorno seguro",
        ],
    },
    {
        id: "calidad-en-mi-trabajo-y-vida-de-calidad",
        title: "Calidad en mi trabajo y vida de calidad",
        subtitle: "Conferencia corporativa",
        description:
            "Conferencia para fortalecer hábitos, enfoque y bienestar: desempeño sostenible con calidad de vida.",
        href: "/files/talleres/sabermas/CONFERENCIACORPORATIVA.pdf",
        videoUrl: "https://www.youtube.com/embed/N8yu8Xtf-VM",
        mainImage: "/images/talleres/CONFERENCIA_CALIDAD_VIDA.jpeg",
        badgeTop: "/files/talleres/confianza/CERTIFICADOPORMAXAN.png",
        badgeBottom: "/files/talleres/confianza/AVALADOPORIMPULSOCOMPLETO.png",
        esquemaImage: "",
        paraQuienImage: "/files/talleres/esparati/ESPARA TI_TALLERES-08.jpg.jpeg",
        duration: "3 horas",
        metaLeft: "Conferencia corporativa",
        badge: "Conferencia",
        keywords: [
            "calidad de vida",
            "hábitos",
            "bienestar",
            "trabajo",
            "desempeño",
            "conferencia",
        ],
    },
    {
        id: "alineamiento-corporativo-nmx-r-025-scfi-2015",
        title: "Alineamiento corporativo con NMX-R-025-SCFI-2015",
        subtitle: "Taller corporativo",
        description:
            "Taller para alinear procesos y cultura organizacional con prácticas de igualdad laboral y no discriminación.",
        href: "/files/talleres/sabermas/CORPORATIVOALINEAMIENTOCONLANORMAMEXICANADEIGUALDADLABORALYNODISCRIMINACION.pdf",
        videoUrl: "https://www.youtube.com/embed/N8yu8Xtf-VM",
        mainImage: "/images/talleres/TALLER_ALINEAMIENTO_NMX025.jpeg",
        badgeTop: "/files/talleres/confianza/CERTIFICADOPORMAXAN.png",
        badgeBottom: "/files/talleres/confianza/AVALADOPORIMPULSOCOMPLETO.png",
        esquemaImage:
            "/files/talleres/comofunciona/CORPORATIVOGESTIONEFICAZDELPROTOCOLODEVIOLENCIALABORAL.jpeg",
        paraQuienImage: "/files/talleres/esparati/ESPARA TI_TALLERES-03.jpg.jpeg",
        duration: "6 horas",
        metaLeft: "Taller corporativo",
        badge: "Taller",
        keywords: [
            "nmx-r-025",
            "igualdad laboral",
            "no discriminación",
            "alineamiento",
            "norma mexicana",
        ],
    },
    {
        id: "criterios-tecnicos-igualdad-salarial",
        title: "Criterios técnicos para la igualdad salarial",
        subtitle: "Taller corporativo",
        description:
            "Taller para identificar brechas salariales y diseñar estrategias de corrección con criterios técnicos y normativos.",
        href: "/files/talleres/sabermas/CORPORATIVODECRITERIOSTECNICOSPARALAIGUALDADSALARIAL.pdf",
        videoUrl: "https://www.youtube.com/embed/N8yu8Xtf-VM",
        mainImage: "/images/talleres/TALLER_IGUALDAD_SALARIAL.jpeg",
        badgeTop: "/files/talleres/confianza/CERTIFICADOPORMAXAN.png",
        badgeBottom: "/files/talleres/confianza/AVALADOPORIMPULSOCOMPLETO.png",
        esquemaImage:
            "/files/talleres/comofunciona/CORPORATIVODECRITERIOSTECNICOSPARALAIGUALDADSALARIAL.jpeg",
        paraQuienImage: "/files/talleres/esparati/ESPARA TI_TALLERES-04.jpg.jpeg",
        duration: "6 horas",
        metaLeft: "Taller corporativo",
        badge: "Taller",
        keywords: [
            "igualdad salarial",
            "brecha salarial",
            "salarios",
            "criterios técnicos",
            "equidad",
        ],
    },
    {
        id: "gestion-eficaz-protocolo-violencia-laboral",
        title: "Gestión eficaz del Protocolo de violencia laboral",
        subtitle: "Taller corporativo",
        description:
            "Taller para implementar y operar protocolos internos de prevención, atención y sanción de violencia laboral.",
        href: "/files/talleres/sabermas/CORPORATIVOPARALAGESTIONEFICAZDELPROTOCOLODEVIOLENCIALABORAL.pdf",
        videoUrl: "https://www.youtube.com/embed/N8yu8Xtf-VM",
        mainImage: "/images/talleres/TALLER_PROTOCOLO_VIOLENCIA.jpeg",
        badgeTop: "/files/talleres/confianza/CERTIFICADOPORMAXAN.png",
        badgeBottom: "/files/talleres/confianza/AVALADOPORIMPULSOCOMPLETO.png",
        esquemaImage:
            "/files/talleres/comofunciona/CORPORATIVOPARALAGESTIONDELPROTOCOLODEVIOLENCIALABORAL.jpeg",
        paraQuienImage: "/files/talleres/esparati/ESPARA TI_TALLERES-05.jpg.jpeg",
        duration: "6 horas",
        metaLeft: "Taller corporativo",
        badge: "Taller",
        keywords: [
            "protocolo",
            "violencia laboral",
            "gestión",
            "atención",
            "sanción",
            "prevención",
        ],
    },
    {
        id: "induccion-igualdad-no-discriminacion-atencion-violencia",
        title: "Inducción a igualdad, no discriminación y atención de violencia",
        subtitle: "Taller corporativo",
        description:
            "Taller para sensibilizar, establecer criterios y promover prácticas de igualdad y no discriminación en equipos.",
        href: "/files/talleres/sabermas/CORPORATIVOINDUCCIONALAIGUALDADALANODISCRIMINACIONYALAATENCIONDELAVIOLENCIALABORAL.pdf",
        videoUrl: "https://www.youtube.com/embed/N8yu8Xtf-VM",
        mainImage: "/images/talleres/TALLER_INDUCCION_IGUALDAD.jpeg",
        badgeTop: "/files/talleres/confianza/CERTIFICADOPORMAXAN.png",
        badgeBottom: "/files/talleres/confianza/AVALADOPORIMPULSOCOMPLETO.png",
        esquemaImage: "",
        paraQuienImage: "/files/talleres/esparati/ESPARA TI_TALLERES-06.jpg.jpeg",
        duration: "3 horas",
        metaLeft: "Taller corporativo",
        badge: "Taller",
        keywords: [
            "igualdad",
            "no discriminación",
            "inducción",
            "violencia laboral",
            "sensibilización",
        ],
    },
    {
        id: "planes-de-accion-igualdad-laboral-no-discriminacion",
        title: "Planes de acción para igualdad laboral y no discriminación",
        subtitle: "Taller corporativo",
        description:
            "Taller para estructurar planes de acción medibles y sostenibles alineados a metas de igualdad laboral.",
        href: "/files/talleres/sabermas/PARALAINTEGRACIONDEPLANESDEACCIONPARALOGRARLAIGUALDADLABORALYLANODISCRIMINACION.pdf",
        videoUrl: "https://www.youtube.com/embed/N8yu8Xtf-VM",
        mainImage: "/images/talleres/TALLER_PLAN_ACCION_IGUALDAD.jpeg",
        badgeTop: "/files/talleres/confianza/CERTIFICADOPORMAXAN.png",
        badgeBottom: "/files/talleres/confianza/AVALADOPORIMPULSOCOMPLETO.png",
        esquemaImage:
            "/files/talleres/comofunciona/CORPORATIVOPARALAINTEGRACIONDEPLANESDEACCIONPARALOGRARLAIGUALDADLABORALYLANODISCRIMINACION.jpeg",
        paraQuienImage: "/files/talleres/esparati/ESPARA TI_TALLERES-07.jpg.jpeg",
        duration: "5 horas",
        metaLeft: "Taller corporativo",
        badge: "Taller",
        keywords: [
            "planes de acción",
            "igualdad laboral",
            "no discriminación",
            "implementación",
            "seguimiento",
        ],
    },
];